### ISSUE TITLE
Sign container images with sigstore cosign

### ISSUE THREAD

**Issue by cpanato** [actions-runner-controller/releases#10]
Will be a good addition if we sign the images using [sigstore cosign](https://github.com/sigstore/cosign)

If the project maintainers are interested on that i can help

**Comment by Link-** [comment]
Thank you @cpanato, at the moment we do not have long term plans to continue maintaining these images. Our direction forward is to only publish: https://github.com/actions/runner/pkgs/container/actions-runner

These images will be deprecated in the future.
