### ISSUE TITLE
Latest tag moved to 22.04 on the last runner release

### ISSUE THREAD

**Issue by kuuji** [actions-runner-controller/releases#2]
I doubt this was intentional but the last self hosted runner published has the latest tag on the 22.04 image.
https://hub.docker.com/layers/summerwind/actions-runner/latest/images/sha256-a2ca08c993b02a33c55074a8a4d2642ace01885087ec49947a1d8669d6737ae9?context=explore

This build pushed the tag https://github.com/actions-runner-controller/releases/actions/runs/3906536846/jobs/6674819227 

I think the 20.04 pushes the tag too but it was overiden by 22.04. This has a bunch of breaking changes because the image is very different.
I pinned to 20.04 on my side for now.

edit:

I just noticed https://github.com/actions-runner-controller/releases/pull/1 will solve this.

**Comment by Link-** [comment]
Thank you @kuuji we're looking into this right now

**Comment by Link-** [comment]
runner images re-released, closing this issue for now.
